// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-cinematic/Cinematic.tsx": () => import("../components/mockups/home-cinematic/Cinematic.tsx"),
  "./components/mockups/home-premium/Premium.tsx": () => import("../components/mockups/home-premium/Premium.tsx")
};
